Repository smaranjitghose/indokhaadyam, pull requests merged in 2022-03, with the labels that each got.

#60 Resolved profile-image bug
  src/pages/Team/Team.jsx
  src/pages/Team/team.css
Labels: PR: reviewed-approved, Medium, JWOC

#61 navbar added to team page
  package-lock.json
  src/pages/Team/Team.jsx
  src/pages/Team/team.css
Labels: PR: reviewed-approved, Medium, JWOC

#56 Feat/footer team page
  src/pages/Team/Team.jsx
  src/pages/Team/team.css
Labels: PR: reviewed-approved, JWOC, Hard

#63 Added navbar in contact page
  src/components/Navbar/Navbar.css
  src/pages/Contact/Contact.jsx
  src/pages/Contact/ContactUs.css
Labels: PR: reviewed-changes-requested, Medium, JWOC

#69 mongo db url added
  .env.example
  package-lock.json
  package.json
  src/index.js
Labels: PR: unreviewed, JWOC, Hard

#65 modified sidebar ui
  src/index.css
Labels: PR: reviewed-changes-requested

#66 Fixed the responsiveness of contact page
  package-lock.json
  package.json
  postcss.config.js
  src/components/Footer/Footer.css
  src/components/Navbar/Navbar.css
  src/index.css
  src/pages/Contact/Contact.jsx
  src/pages/Contact/ContactUs.css
  src/pages/Home/Home.js
  tailwind.config.js
Labels: PR: unreviewed

#75 navbar bug resolved
  src/pages/Contact/Contact.jsx
Labels: PR: unreviewed

#78 recipe form added
  src/App.js
  src/pages/RecipeForm/RecipeForm.css
  src/pages/RecipeForm/RecipeForm.js
Labels: PR: unreviewed

#79 CRUD operations updated
  src/Models/Recipe.js
  src/Routes/index.js
  src/controllers/recipeController.js
  src/index.js
Labels: PR: unreviewed

#80 recipe data backend
  package-lock.json
  package.json
  src/index.js
Labels: PR: unreviewed

#81 Recipe data front-end updated
  package-lock.json
  package.json
  src/App.js
  src/components/Navbar/Navbar.js
  src/components/Navbar/mobilenavbar.js
  src/components/TopCategory/TopCategory.js
  src/components/TopCategory/topCategory.css
  src/pages/RecipeData/recipeData.css
  src/pages/RecipeData/recipeData.js
  src/pages/RecipeForm/RecipeForm.css
  src/pages/RecipeForm/RecipeForm.js
Labels: PR: unreviewed
