Repository smaranjitghose/indokhaadyam, pull requests merged in 2022-02, with the labels that each got.

#9 Updated Footer Design
  package-lock.json
  package.json
  src/App.css
  src/components/Footer.js
  src/globalStyles.js
Labels: PR: reviewed-approved

#21 Refactored the file Structure.
  package-lock.json
  src/App.js
  src/assets/banner.png
  src/pages/Home.js
  src/pages/Home.jsx
Labels: PR: reviewed-approved

#20 issue #13 logo added
  assets/logo/Indokhadyaam.png
  assets/logo/Indokhadyaam_bk.png
  assets/logo/Indokhadyaam_bk_trans.png
  assets/logo/Indokhadyaam_trans.png
Labels: PR: reviewed-changes-requested, JWOC

#30 counter effect aded
  package-lock.json
  src/components/Home.js
Labels: PR: unreviewed

#28 Added Contact Page and did routing for the same
  src/App.js
  src/components/Contact.jsx
  src/components/Textarea.jsx
  src/pages/Home.jsx
  src/styles/ContactUs.css
Labels: PR: unreviewed

#25 🚀 feat: Added Teams Page
  package.json
  src/App.js
  src/assets/anush_bhatia.png
  src/assets/smaranjit_ghose.jpg
  src/pages/Team.jsx
  src/styles/team.css
Labels: PR: unreviewed, JWOC

#32 Added routing for home , contact and features page
  src/App.js
  src/styles/ContactUs.css
Labels: PR: unreviewed

#33 Modified the favicon
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/logo512.png
Labels: PR: unreviewed

#36 Added Basic Navbar
  package.json
  src/App.css
  src/components/Navbar/Navbar.js
  src/components/Navbar/menuToggle.jsx
  src/components/Navbar/mobilenavbar.js
  src/globalStyles.js
  src/pages/Home.jsx
Labels: PR: unreviewed

#42 Inter font Updated
  package.json
  src/App.css
  src/components/Footer.js
  src/components/Home.css
  src/components/Home.js
  src/components/Navbar/Navbar.js
  src/components/Navbar/mobilenavbar.js
  src/index.css
  src/styles/ContactUs.css
  src/styles/team.css
Labels: PR: reviewed-approved

#43 Separate CSS files updated
  src/components/Footer.css
  src/components/Footer.js
  src/components/Home.css
  src/components/Home.js
  src/components/Navbar/Navbar.css
  src/components/Navbar/Navbar.js
  src/components/Navbar/menuToggle.css
  src/components/Navbar/menuToggle.jsx
  src/components/Navbar/mobilenavbar.css
  src/components/Navbar/mobilenavbar.js
Labels: PR: unreviewed

#45 feat: created the 404 Error Page
  package-lock.json
  src/App.js
  src/assets/Error404.png
  src/components/Contact.jsx
  src/pages/PageNotFound.jsx
  src/styles/error404.css
Labels: JWOC, Hard

#55 Feat/footer contact page
  src/App.js
  src/assets/Error404.png
  src/assets/images/error/Cheese.png
  src/assets/images/error/Error404.gif
  src/components/Contact.jsx
  src/components/Footer.css
  src/pages/Home.jsx
  src/pages/PageNotFound.jsx
  src/styles/error404.css
Labels: PR: unreviewed

#53 update: 404 Page
  src/App.js
  src/assets/Error404.png
  src/assets/images/error/Cheese.png
  src/assets/images/error/Error404.gif
  src/pages/PageNotFound.jsx
  src/styles/error404.css
Labels: PR: reviewed-changes-requested

#57 Updated Image responsiveness
  src/styles/topCategory.css
Labels: PR: unreviewed
